#!/usr/bin/bash -euo pipefail

function log { echo "$@" >&2; }
function run { log "+ $@"; "$@"; }

run sh <(curl -L https://nixos.org/nix/install) --daemon

# activate Nix set up in current shell
if [[ -f ~/.bash_profile ]]; then
    run source ~/.bash_profile
elif [[ -f ~/.zshrc ]]; then
    run source ~/.zshrc

run nix-channel --add https://github.com/nix-community/home-manager/archive/master.tar.gz home-manager
run nix-channel --update

run export NIX_PATH=$HOME/.nix-defexpr/channels:/nix/var/nix/profiles/per-user/root/channels${NIX_PATH:+:$NIX_PATH}

run nix-shell '<home-manager>' -A install

# remove autogenerated config
run rm ~/.config/nixpkgs/home.nix

run ln -s ~/home/home.nix ~/.config/nixpkgs/home.nix

